### ISSUE TITLE
fix problem when missing custom variables

### ISSUE THREAD

**Issue by marwin1991** [logchange/valhalla#19]
```
[INFO]  )
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/valhalla/__main__.py", line 4, in <module>
    start()
  File "/opt/valhalla/valhalla/main.py", line 27, in start
    init_str_resolver_custom_variables(config.variables)
  File "/opt/valhalla/valhalla/common/resolver.py", line 32, in init_str_resolver_custom_variables
    CUSTOM_VARIABLES_DICT.update(variables)
TypeError: 'NoneType' object is not iterable
```

**Comment by witx98** [comment]
Resolved in https://github.com/logchange/valhalla/pull/23
